application: djangaethinkamisample
version: 20151228
runtime: python27
api_version: 1
threadsafe: true

# for --sandbox=remote migrate/loaddata, etc
builtins:
- remote_api: on

handlers:
- url: /_ah/(mapreduce|queue|warmup).*
  script: myproject.wsgi.application
  login: admin

- url: /.*
  script: myproject.wsgi.application
  
libraries:
- name: yaml
  version: "3.10"